### ISSUE TITLE
unable to connect UI to the socket-server

### ISSUE THREAD

**Issue by bhargodevarya** [codesling/codesling.io#36]
In the LandingPage.js, under ComponentDidMount, id is being set as after receiving it from the socket-server.
In my machine it is unable to connect to the to the socket-server.
I have followed the instructions from the getting started section of the developer documentation.
when I log the information about socket, it comes out to be in disconnected state.
my backend servers are up.
Attaching the screenshots of the same.

![backend_servers](https://user-images.githubusercontent.com/16055491/32141950-c10661d8-bcb2-11e7-99d5-8eb767c4649a.PNG)

![issue1](https://user-images.githubusercontent.com/16055491/32141935-59c04106-bcb2-11e7-9e00-42765393564a.PNG)

**Comment by J6K** [comment]
<img width="1046" alt="screen shot 2017-10-30 at 11 59 03 am" src="https://user-images.githubusercontent.com/24511251/32190078-dbc56e94-bd69-11e7-8db9-50c7ae20820a.png">

I'm not quite sure what your issue is? 
Are you not receiving the logs indicating that the client connected?

**Comment by obber** [comment]
This is due to an inconsistency in the env script builder introduced in this commit: https://github.com/codesling/codesling.io/commit/cdfb34155bdf0843ea728365d7d0efe649af96a8#diff-666fed852f993251d024f00697e19ce0

I forgot to change `config/env.sample.js` to put an `_` before the envPrefix.

PR submitted:
https://github.com/codesling/codesling.io/pull/38

**Comment by obber** [comment]
Closing, addressed by https://github.com/codesling/codesling.io/pull/38

You'll need to pull in the changes and rerun `cp config/env.sample.js config/env.js && yarn env development`.
